### PR TITLE
Fix #34 and #35

### LINKED ISSUE #34: Peer dependency is not right
Hey, thanks a lot for the work on #28. It looks like everything's working, but it looks like the peer dependency listing didn't get re-updated, and it's a little misleading:

```
warning " > semantic-release-github-pr@5.1.0" has incorrect peer dependency "semantic-release@13.4.1 - 15.6.x".
```

### PR DESCRIPTION
**Pull request by mysterycommand**
Hey there, not sure if you're open to PRs (I don't see a `CONTRIBUTING` in here), but I thought I'd give this a shot. I think it works? Tests all pass anyway, let me know what you think!

### CODE REVIEW

**Comment by mysterycommand** [comment]
Hey there @pmowrer, anything missing here? Happy to make changes, or tweak it. Just lmk!

**Comment by mysterycommand** [comment]
Hello? Happy holidays!

**Comment by mysterycommand** [comment]
🏏s?

**Comment by mysterycommand** [comment]
Maybe now that the holidays are passed and we're on our way in to spring it's time to dust this old PR off and merge it on in? 😃😸🙏

**Review by egucciar — APPROVED** [review]
I think this looks good, is non breaking, and improves the ability to use more recent versions of Semantic Release.

**Comment by brownjedi** [comment]
any idea when this will be merged?

**Comment by pmowrer** [comment]
@mysterycommand Thanks so much for identifying these issues! I'm going to finally get this all fixed today

**Comment by pmowrer** [comment]
The plugin was just updated the work with `semantic-release` v16+!  Turns out, with all the changes to `semantic-release`, we don't need the retrieve the `gitHead` the way it was done previously anymore. Thanks for again for the fixes anyway!

**Pull request closed without merging**
