### PR TITLE
Fix missing context

### PR DESCRIPTION
**Pull request by pmowrer**

### CODE REVIEW

**Comment by pmowrer** [comment]
[//]: # (semantic-release-github-pr 246bcf7d7f999b4b938c254f12c26f325664dfa8 semantic-release-github-pr v5.0.6)
Merging this PR will publish the following release:

## [5.0.6](https://github.com/Updater/semantic-release-github-pr/compare/v5.0.5...v5.0.6) (2018-09-10)


### Bug Fixes

* pass `context` to `resolveConfig` ([9dfea96](https://github.com/Updater/semantic-release-github-pr/commit/9dfea96)), closes [#28](https://github.com/Updater/semantic-release-github-pr/issues/28)

**Comment by pmowrer** [comment]
[//]: # (semantic-release-github-pr 246bcf7d7f999b4b938c254f12c26f325664dfa8 semantic-release-github-pr v5.0.6)
Merging this PR will publish the following release:

## [5.0.6](https://github.com/Updater/semantic-release-github-pr/compare/v5.0.5...v5.0.6) (2018-09-10)


### Bug Fixes

* pass `context` to `resolveConfig` ([9dfea96](https://github.com/Updater/semantic-release-github-pr/commit/9dfea96)), closes [#28](https://github.com/Updater/semantic-release-github-pr/issues/28)

**Comment by pmowrer** [comment]
[//]: # (semantic-release-github-pr 246bcf7d7f999b4b938c254f12c26f325664dfa8 semantic-release-github-pr v5.0.6)
Merging this PR will publish the following release:

## [5.0.6](https://github.com/Updater/semantic-release-github-pr/compare/v5.0.5...v5.0.6) (2018-09-10)


### Bug Fixes

* pass `context` to `resolveConfig` ([9dfea96](https://github.com/Updater/semantic-release-github-pr/commit/9dfea96)), closes [#28](https://github.com/Updater/semantic-release-github-pr/issues/28)

**Comment by updaterci** [comment]
[//]: # (semantic-release-github-pr 13399f8aa1b0c5080a32f75f018e84234b673240 semantic-release-github-pr v5.1.0)
Merging this PR will publish the following release:

# [5.1.0](https://github.com/Updater/semantic-release-github-pr/compare/v5.0.7...v5.1.0) (2018-09-11)


### Bug Fixes

* pass `context` to `resolveConfig` ([376a411](https://github.com/Updater/semantic-release-github-pr/commit/376a411)), closes [#28](https://github.com/Updater/semantic-release-github-pr/issues/28)


### Features

* allow defining multiple `generateNotes` plugins ([abe1f7c](https://github.com/Updater/semantic-release-github-pr/commit/abe1f7c))

**Pull request merged**
